### PR TITLE
Fix build from source for newer node versions:

### PR DESCRIPTION
**Pull request by Granjow**
- Use sha256 (instead of sha1, which is not provided anymore) as checksum
- Change package name from nodejs to node to meet standard names
- Split cmd.run into single commands (names = [] does not seem to be present anymore in Salt)
- Drop npm because it is included in npm

This probably does not meet your guidelines yet. Please provide some feedback so I can improve this formula and get it merged. Installation just does not work anymore for current node.js versions. Is there perhaps a better way? node.js is widely used, but this formula is rather abandoned.

### CODE REVIEW

**Comment by gravyboat** [comment]
In general I'm a fan of these changes. My main concern is the removal of the source installation file.

**Comment by Granjow** [comment]
You mean the file for npm?

Do you think it makes sense to keep the old code for backwards compatibility, if someone wants to install a prehistoric node version? :)

I'm not quite sure on how to proceed. Some improvements still have to be made for the current version, like ensuring that it is not built twice. And if old versions have to be supported, this has to be tested somehow …

**Comment by gravyboat** [comment]
@Granjow Yeah the npm file stuff. I would prefer if it was backwards compatible, but if it can't be, then it can't be. As a heads up I also just merged in this. Old versions don't HAVE to be supported, I'd rather merge improvements than support old releases.

**Comment by Granjow** [comment]
@gravyboat I updated the formula, now it checks if node is already present and only downloads/compiles stuff if not.

Regarding backwards compatibility, actually you are right, and if somebody needs the old version, then we have version control!

Anything that is still missing? :)

**Comment by gravyboat** [comment]
No this looks good to me, thank you.

**Pull request merged**
