### PR TITLE
Markdown link fix

### PR DESCRIPTION
**Pull request by Granjow**
Sorry, I was about 30 seconds late with my commit, so here another pull request because I messed up the links in the readme. Thanks for merging!

### CODE REVIEW

**Comment by gravyboat** [comment]
No worries, thanks for fixing this! Do you want to rebase so that c66a98a isn't part of this PR?

**Comment by Granjow** [comment]
Oh, sure. I will try tomorrow. :)

**Comment by Granjow** [comment]
Okay, I have created a mess before because I did a `push --force` 30 seconds after you merged, which caused my history to look slightly funny with nearly duplicated commits. Just for general amusement:

treebeforerebasing

`git rebase master mdFix` then fixed the problem. Thanks for the hint, I would otherwise just have cherry-picked the commit or copy/pasted it on a new branch or used some other workaround. :D Hope it is good now!

**Comment by gravyboat** [comment]
Looks good to go! Thanks for fixing that up. Rebase is seriously amazing.

**Comment by Granjow** [comment]
Yes :-] Thanks for the merge!

**Pull request merged**
