### PR TITLE
Allow Debian to install from the Nodesource repository

### PR DESCRIPTION
**Pull request by malept**
Also fixes the `npm_requirement` mapped variable when using that repository.

### CODE REVIEW

**Comment by bogdanr** [comment]
I tested this and it works just fine.

**Comment by gravyboat** [comment]
@malept Looks like this one slipped through the cracks. Could you please rebase?

**Comment by malept** [comment]
Will do.

**Comment by malept** [comment]
@gravyboat rebased.

**Comment by gravyboat** [comment]
Thanks!

**Pull request merged**
