### PR TITLE
Import YAML with context

### PR DESCRIPTION
**Pull request by Lucianovici**
Import with context to avoid errors like:

```
[CRITICAL] Rendering SLS ... failed: Jinja variable 'grains' is undefined
```

```
[CRITICAL] Rendering SLS ... failed: Jinja variable 'salt' is undefined
```

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
@Lucianovici  could you update both commit messages to comply with conventional commit standard.
 see https://www.conventionalcommits.org/en/v1.0.0/#summary  CI is failing.

**Comment by Lucianovici** [comment]
@noelmcloughlin Is that important to fix this, the solution of renaming pushed commit messages is not ideal (forcing to push) - is there another way I am not aware of?

**Comment by noelmcloughlin** [comment]
> Is it important to fix this?

Yes. All automation based on conventional commits (widely used today instead of unconventional commits) breaks. Someone would have to change those commit messages to get CI and Semantic Release working.

**Comment by Lucianovici** [comment]
@noelmcloughlin Since I am a casual committer, can we do as advice here please?
https://www.conventionalcommits.org/en/v1.0.0/#do-all-my-contributors-need-to-use-the-conventional-commits-specification

**Comment by noelmcloughlin** [comment]
I'm not maintainer, just passing by, so its extra workload.  I think its possible, I've never done that, I could try I guess.
https://github.com/saltstack-formulas/node-formula/blob/79081c913440a83104ed3b7347c777e2eb9f4773/CODEOWNERS#L11-L12

**Comment by noelmcloughlin** [comment]
Okay, that did not work, I'll try to remember to open a new PR to fix your commit messages. Please use conventional commits in future, its considered impolite to use unconventional commits these days.

**Comment by Lucianovici** [comment]
Alright thank you, I will use the convention from now on. But why didn't it work, I just alter the history and force push it?

**Comment by myii** [comment]
Just noting that this is an example of a patch for this Salt regression as mentioned here:

* https://github.com/saltstack/salt/issues/60188#issuecomment-843004346

**Pull request merged**
